# Generated by Django 2.1.7 on 2019-03-20 14:50

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_countries.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('access_control', '0003_employee_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wireless', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('country_of_origin', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('brand_number', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(help_text='Help describe this brand')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('reorder_quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='stock_categoryplugin', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CategoryPluginSearch',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='stock_categorypluginsearch', serialize=False, to='cms.CMSPlugin')),
                ('slug', models.SlugField(blank=True, default='example', help_text='This slug is used to map the URL of this category at the front end', max_length=128, null=True)),
                ('search_field', models.CharField(help_text='HINT: Enter name of category for the page to find corresponding plugins', max_length=128, verbose_name='Search name')),
                ('page_url', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(choices=[('Mac', 'macOS'), ('Window', 'windowsOS')], max_length=32, verbose_name='Operating System')),
                ('type', models.CharField(choices=[('Desktop', 'desktop'), ('Laptop', 'laptop'), ('Mobile', 'mobile'), ('Tablet', 'tablet')], max_length=32)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_images', to=settings.FILER_IMAGE_MODEL)),
            ],
            managers=[
                ('computers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='stock_inventory', serialize=False, to='cms.CMSPlugin')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('item', models.CharField(help_text='Create an item at the top level of classification', max_length=128, verbose_name='Item')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_images', to=settings.FILER_IMAGE_MODEL)),
                ('page_url', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ItemBaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=1024)),
                ('name', models.CharField(max_length=32)),
                ('tags', models.CharField(max_length=32)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('screen_size', models.CharField(blank=True, max_length=128, null=True)),
                ('overall_width', models.CharField(blank=True, max_length=128, null=True)),
                ('overall_height', models.CharField(blank=True, max_length=128, null=True)),
                ('color', models.CharField(blank=True, max_length=128, null=True)),
                ('extras', models.TextField(blank=True, max_length=128, null=True)),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kind_audio', to='stock.AudioExtra')),
            ],
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peripherals', to='stock.Computer')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenMountingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, max_length=1064, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, max_length=1064, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='AudioVisual',
            fields=[
                ('itembasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stock.ItemBaseModel')),
                ('status', models.CharField(blank=True, choices=[('Damaged', 'damaged'), ('Out of Stock', 'out of stock')], max_length=64, null=True)),
                ('is_audio_solution', models.BooleanField(default=False)),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_visuals', to='stock.Brand')),
            ],
            bases=('stock.itembasemodel',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categorybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stock.CategoryBase')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Naam')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Beschrijving')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_images', to=settings.FILER_IMAGE_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='stock.Inventory', verbose_name='Inventory')),
            ],
            options={
                'verbose_name_plural': 'Categorieën',
            },
            bases=('stock.categorybase',),
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('itembasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stock.ItemBaseModel')),
                ('assigned_date', models.DateField(blank=True, null=True, verbose_name='Date assigned')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='Date returned')),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('model_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Model number')),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Serial number')),
                ('warrant_expiry_date', models.DateField(blank=True, null=True, verbose_name='Date of Warrant Expiry')),
            ],
            options={
                'verbose_name_plural': 'Details',
            },
            bases=('stock.itembasemodel',),
        ),
        migrations.AddField(
            model_name='vendor',
            name='item',
            field=models.ManyToManyField(to='stock.ItemBaseModel'),
        ),
        migrations.AddField(
            model_name='kind',
            name='mounting_method',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kind_mounting', to='stock.ScreenMountingMethod'),
        ),
        migrations.AddField(
            model_name='kind',
            name='screen_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kind_screen', to='stock.ScreenType'),
        ),
        migrations.AddField(
            model_name='categoryplugin',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Inventory'),
        ),
        migrations.CreateModel(
            name='PeripheralDetails',
            fields=[
                ('details_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stock.Details')),
                ('is_peripheral', models.BooleanField(default=True)),
            ],
            bases=('stock.details',),
        ),
        migrations.AddField(
            model_name='details',
            name='assigned_employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access_control.Employee', verbose_name='Assigned Employee'),
        ),
        migrations.AddField(
            model_name='computer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='stock.Category'),
        ),
        migrations.AddField(
            model_name='computer',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='stock.Details'),
        ),
        migrations.AddField(
            model_name='categoryplugin',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Category'),
        ),
        migrations.AddField(
            model_name='audiovisual',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Category'),
        ),
        migrations.AddField(
            model_name='audiovisual',
            name='images',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_visuals_images', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='audiovisual',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_visuals', to='stock.Kind', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='peripheral',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peripherals', to='stock.PeripheralDetails', verbose_name='Peripheral Details'),
        ),
        migrations.AddIndex(
            model_name='audiovisual',
            index=models.Index(fields=['brand'], name='stock_audio_brand_i_b3c9af_idx'),
        ),
    ]
