# Generated by Django 2.1.7 on 2019-03-01 11:58

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import stock.models.items.assets.computer


class Migration(migrations.Migration):

    dependencies = [("stock", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="AudioExtra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_wireless", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="AudioVisual",
            fields=[
                (
                    "itembasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="stock.ItemBaseModel",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Damaged", "damaged"),
                            ("Out of Stock", "out of stock"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                ("is_audio_solution", models.BooleanField(default=False)),
                (
                    "images",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=stock.models.items.assets.computer.get_upload_path,
                    ),
                ),
            ],
            bases=("stock.itembasemodel",),
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "country_of_origin",
                    django_countries.fields.CountryField(max_length=746, multiple=True),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("description", models.TextField(help_text="Help describe this brand")),
            ],
        ),
        migrations.CreateModel(
            name="Kind",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "screen_size",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "screen_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Folding", "folding"),
                            ("Wall", "tripod"),
                            ("LCD", "lcd"),
                            ("LED", "led"),
                            ("Plasma", "plasma"),
                            ("OLED", "oled"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "mounting_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Wall or Ceiling", "wall or ceiling"),
                            ("Wall", "tripod"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "overall_width",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "overall_height",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("color", models.CharField(blank=True, max_length=128, null=True)),
                ("extras", models.TextField(blank=True, max_length=128, null=True)),
                (
                    "audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.AudioExtra",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="audiovisual",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.Brand",
            ),
        ),
        migrations.AddField(
            model_name="audiovisual",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.Category",
            ),
        ),
        migrations.AddField(
            model_name="audiovisual",
            name="kind",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.Kind",
                verbose_name="Type",
            ),
        ),
        migrations.AddIndex(
            model_name="audiovisual",
            index=models.Index(fields=["brand"], name="stock_audio_brand_i_b3c9af_idx"),
        ),
    ]
