# Generated by Django 2.1.7 on 2019-03-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190321_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryplugin',
            name='category',
        ),
        migrations.AlterField(
            model_name='categoryplugin',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_inventory_category', to='stock.Inventory'),
        ),
    ]
