# Generated by Django 2.1.7 on 2019-03-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("stock", "0002_auto_20190301_1158")]

    operations = [
        migrations.RenameField(
            model_name="brand", old_name="serial_number", new_name="brand_number"
        ),
        migrations.AddField(
            model_name="audiovisual",
            name="serial_number",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
