# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-18.10'

steps:
- script: |
    pip install -r requirements.txt
  displayName: 'Install Requirements'

- script: |
    python -m pip install flake8
    flake8 .
  displayName: 'Run lint tests'
