image: python:3.5.1

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements.txt
    - step:
        name: Test
        deployment: test
        script:
        - echo "Test"
        - pip install -r requirements.txt
        - python manage.py test
        - python -m pip install flake8
        - flake8 .
