INVENTORY = dict(
    audio_visual=dict(item="Audiovisuele apparatuur"),
    binding_material=dict(item="Bindmiddelen en klemborden"),
    boards=dict(item="Borden en schildersezels"),
    calendars=dict(item="Kalenders en planners"),
    clips=dict(item="Clips, drukknoppen en elastiekjes"),
    clocks=dict(item="Klokken en tijdkloksystemen"),
    computers=dict(
        item="Computerbenodigdheden en media",
        categories=[
            "Hubs voor cd en dvd",
            "Opslag van cd's en dvd's",
            "CD-, DVD- en USB-duplicators",
            "Cd's en dvd's",
            "Computer kabeladapters en splitsers",
            "Computerkabels",
            "Computer muizen",
            "Computermonitor armen",
            "Filters voor computerscherm",
            "Bureaus en staanders",
            "Flash-drives en geheugenkaarten",
            "GPIB-netwerkhardware",
            "KVM-switches",
            "Toetsenbord- en muissets",
            "Toetsenborden",
            "Laptoptassen en koffers",
            "Muismatten",
            "Opladers voor smartphones en tablets",
            "Hoesjes voor tablets, houders en schermbeschermers",
            "Tablet-stylus en touchscreen-pennen",
            "USB-kabels",
            "USB-connectoren en hubs",
        ],
    ),
    covers=dict(item="Covers, schermen en kaders van documenten"),
    maps=dict(item="Bestandsmappen en kaders"),
    flags=dict(item="Vlaggen, vlaggenmasten en accessoires"),
    print_material=dict(item="Inkt en tonercartridges"),
    laminate=dict(item="Lamineer- en bindapparatuur"),
    cleaning_stuf=dict(item="Kantoorschoonmaakbedrijven"),
    office_machines=dict(item="Kantoormachines en -apparatuur"),
    office_paper=dict(item="Kantoorpapier en laptops"),
    stamps=dict(item="Stempels en inktkussens"),
    batteries=dict(item="Standaard batterijen"),
    staples=dict(item="Nietmachines, tapedispensers en perforatoren"),
)

image = "media/Computerbenodigheden/2019/02/25/_49A2386.jpg"
