# Generated by Django 2.1.7 on 2019-03-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("access_control", "0002_auto_20190220_1436")]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        )
    ]
